### ISSUE TITLE
Fix type piracy with Colors.RGB

### ISSUE THREAD

**Issue by j-fu** [WIAS-PDELib/GridVisualize.jl#36]
Colors.RGB gets methods for string and symbols in GridVisualizeTools.
This is type piracy. May be can be replace by parse() (see Colors.jl docs).

**Comment by jpthiele** [comment]
I think the only real occurence in this repo might be https://github.com/WIAS-PDELib/GridVisualize.jl/blob/832bac83e289f91f8b224aee4525ab65fe625b5f/src/meshcat.jl#L166

Otherwise `rgbtuple` is used which is defined in [GridVisualizeTools.jl/src/colors.jl](https://github.com/WIAS-PDELib/GridVisualizeTools.jl/blob/d38727430bee4b4ddb4619d5fab81c65d9f5fd1e/src/colors.jl#L99)
so I think we should rewrite that function to use `parse`, right?

**Comment by jpthiele** [comment]
See: https://github.com/WIAS-PDELib/GridVisualizeTools.jl/pull/12
